### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by rconde01** [BorisSchaeling/boost-process#1]
Hey Boris,
   I was trying to trace the status of the project and couldn't really figure out where things stand. What are the open issues that need to be resolved before another boost review can be done?

**Comment by BorisSchaeling** [comment]
Good question. :) I didn't look at Boost.Process for nearly two years (nor anybody else as far as I know). From a technical point of view I believe we gathered enough experience in the last eight years to implement a process management library in C++ correctly (the library here in GitHub comes with lots of unit tests which are all passed successfully). From a usability point of view the big question is whether the library's API meets user expectations. Here more feedback from (potential) users would be very useful. For example, have a look at http://www.highscore.de/boost/process0.5/boost_process/tutorial.html. Is this what you expect from a well-designed Boost C++ library? Is it too complicated? Would you prefer to launch child processes differently? Do you miss features you would expect a process management library to provide? Feel free to send your feedback to the Boost developers mailing list. Any discussions help - and if only to revitalize interest in Boost.Process. :)
