### ISSUE TITLE
Add license information and link to http://www.highscore.de/boost/process/index.html to README

### ISSUE THREAD

**Issue by mkroehnert** [BorisSchaeling/boost-process#6]
Hi,

it would be nice to have the license information mentioned in the README file.
Linking to http://www.highscore.de/boost/process/index.html would probably also be a good idea..

Currently, license information can only be obtained by looking at the header files which mention a `LICENSE_1_0.txt` file or a link to the boost website.

**Comment by BorisSchaeling** [comment]
For anyone stumbling upon this ticket: The documentation for the current version of Boost.Process (as it can be found here in GitHub) is at http://www.highscore.de/boost/process0.5/.

**Comment by mkroehnert** [comment]
Thanks for the info @BorisSchaeling.
Nevertheless, it would be more convenient to add this information to README file as this is the most prominent place for such information (people are less likely to search the issue tracker for documentation links).

Would it also be possible to add the missing `LICENSE_1_0.txt` to the repo?

**Comment by mkroehnert** [comment]
Thank you very much.
This makes the information much more accessible.

**Comment by BorisSchaeling** [comment]
Thank you for having opened this issue! Nobody is actively working on the library these days. But a little bit activity hopefully keeps the library alive (there went too much time and effort into developing this library, and there is too much domain knowledge manifested in the library that it would be shame if it was all for nothing).
